name: bottleshopdeliveryapp
description: Bottleshop 3 Veze Delivery App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.16
  get: ^3.4.0
  get_storage: ^1.2.1
  provider: ^4.3.1
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.1
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_staggered_grid_view: ^0.3.1
  sticky_headers: ^0.1.8+1
  datetime_picker_formfield: ^1.0.0
  animations: ^1.1.1
  logger: ^0.9.1
  cached_network_image: ^2.2.0+1
  snack: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.9.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.4.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
