on:
  push:
    branches:
    - master
name: Flutter CD
jobs:
  bild:
    name: Build APK and PWA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: echo -n $SIGNING_KEY | base64 -di > android/app/key.jks
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - run: flutter pub get
    - run: flutter build web
    - run: flutter build apk --split-per-abi
      env:
        STORE_PWD: ${{ secrets.STORE_PWD }}
        STORE_PATH: key.jks
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    - name: Deploy to Firebase Hosting
      id: firebase-hosting-deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:eshop
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: v0.1.${{ github.run_number }}
        release_name: Pre-realease master-{{ github.run_id }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Deploy to Firebase App Distribution
      id: firebase-app-distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: android-testers
        file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
