on:
  push:
    branches:
    - master
name: Flutter CD
jobs:
  bild:
    name: Build APK and PWA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo -n $SIGNING_KEY | base64 -di > android/app/${{ secrets.STORE_PATH }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - run: flutter build apk --split-per-abi --build-name=0.1.${{ github.run_number }} --build-number=${{ github.run_id }}
        env:
          STORE_PWD: ${{ secrets.STORE_PWD }}
          STORE_PATH: ${{ secrets.STORE_PATH }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      - name: Deploy to Firebase Hosting
        id: firebase-hosting-deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:eshop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          commit: master
          tag: v0.1.${{ github.run_number }}
          name: master@${{ github.run_number }}
          draft: false
          prerelease: true
          allowUpdates: true
          artifactContentType: application/vnd.android.package-archive
          token: ${{ secrets.RELEASE_TOKEN }}
