name: Flutter CD
on:
  push:
    branches:
      - master
jobs:
  bild:
    name: Build APK and PWA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo -n $SIGNING_KEY | base64 -di > android/app/${{ secrets.STORE_PATH }}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - run: flutter build apk --split-per-abi --build-name=0.1.${{ github.run_number }} --build-number=${{ github.run_id }}
        env:
          STORE_PWD: ${{ secrets.STORE_PWD }}
          STORE_PATH: ${{ secrets.STORE_PATH }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      - name: Deploy to Firebase Hosting
        id: firebase-hosting-deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:eshop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v0.1.${{ github.run_number }}
          release_name: Pre-realease master@${{ github.run_number }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: app-arm64-v8a-release.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
